### ISSUE TITLE
Add command to explicitly delete cached colorscheme

### ISSUE THREAD

**Issue by NGStaph** [scaryrawr/winwal#6]
Thank you for your wonderful script. 
I've been using 
`Invoke-WebRequest -Uri https://source.unsplash.com/random -OutFile C:\Users\jayma\Documents\wallpaper.jpg`
to download a wallpaper and save it to the _same file_ every time. On Linux I'd use `wal -c & wal -i path/to/wallpaper.jpeg` to resolve this. 

I'm new to PowerShell scripting. How could I regenerate the colour scheme every time?

**Comment by NGStaph** [comment]
Ideally I want this to run automatically on a wallpaper change, how could I got about doing that? power automate?

**Comment by scaryrawr** [comment]
I'm not familiar with triggering on wallpaper change. I think for your use case you can do something like:

```powershell
Invoke-WebRequest -Uri https://source.unsplash.com/random -OutFile C:\Users\jayma\Documents\wallpaper.jpg
Update-WalTheme -Image C:\Users\jayma\Documents\wallpaper.jpg
```

**Comment by scaryrawr** [comment]
For clearing the cache, you can still use pywal `wal -c` since this is just wrapping around pywal.

pywal doesn't perform it's actions correctly on Windows, so the PowerShell is doing that after using pywal to generate the cache.

**Comment by cfuendev** [comment]
`wal -c` didn't work for me, for some reason. Nor did monkey-patching the `-c` flag directly into the winwal source. Here's a different approach if you're in my situation:

**Manual**

You can run..

```pwsh
Get-ChildItem -Path $env:TEMP -Filter "TranscodedWallpaper*.json" -File | Remove-Item -Force
Get-ChildItem -Path $env:TEMP -Filter "TranscodedWallpaper" -File | Remove-Item -Force
```

..before running `Update-WalTheme`, to straight up delete the cached wallpaper and color scheme.

**Patch**

Or monkey-patch the source code (`path_to_winwal\winwal\windows-pwsh\Update-WalTheme.ps1`) so that the PowerShell command always forces a color scheme re-generation.

Example:

```pwsh
<#
.DESCRIPTION
    Updates wal templates and themes using a new image or the existing desktop image
#>
function Update-WalTheme {
  param(
    # Path to image to set as background, if not set current wallpaper is used
    [string]$Image,
    [string]$Backend = 'wal'
  )

  # Start of my patch ---

  Get-ChildItem -Path $env:TEMP -Filter "TranscodedWallpaper*.json" -File | Remove-Item -Force
  Get-ChildItem -Path $env:TEMP -Filter "TranscodedWallpaper" -File | Remove-Item -Force

  # --- End of my patch

  . $PSScriptRoot/../common/Update-WalThemeInternal.ps1
  Update-WalThemeInternal -Image $Image -Backend $Backend
}

Export-ModuleMember -Function Update-WalTheme
```

You could hide those two `Get-ChildItem` commands behind a flag/argument if you want to further customize winwal.
